version: "3.8"

services:
  # client:
  #   build: ./Insta_Mern_Cleint
  #   ports:
  #     - 3000:3000

  server:
    build: ./Insta_Mern_Server
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - './data:/data/db'
    restart: always
  
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - client
  #     # - server
  #     # - mongo
