services:
  - type: web
    name: server
    # env: node
    # buildCommand: cd Insta_Mern_client;npm install
    # startCommand: cd Insta_Mern_client;npm start
    # plan: free
    # autoDeploy: false
    env: docker
    rootDir: ./

  - type: pserv
    name: mongodb
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 1
